Repository sul-dlss/dor-services-app, pull requests merged in 2019-09, with the labels that each got.

#358 SymphonyReader validates num bytes in resp body
  app/controllers/marcxml_controller.rb
  app/controllers/metadata_refresh_controller.rb
  app/controllers/objects_controller.rb
  app/models/symphony_reader.rb
  spec/controllers/marcxml_controller_spec.rb
  spec/controllers/objects_controller_spec.rb
  spec/models/symphony_reader_spec.rb
  spec/requests/metadata_refresh_spec.rb
Labels: SDR Fall 2019, descMd problems

#372 surface better error message in ObjectsController
  app/controllers/objects_controller.rb
  spec/controllers/objects_controller_spec.rb
Labels: SDR Fall 2019, tech debt

#373 alert honeybadger for incomplete response from Symphony
  app/models/symphony_reader.rb
  spec/models/symphony_reader_spec.rb
Labels: SDR Fall 2019, descMd problems

#378 add registrationWF to seeds
  lib/tasks/seeds/druid:sh219xb1690.xml
  lib/tasks/seeds/druids
Labels: SDR Fall 2019, tech debt

#380 Symphony responses aren't always status 200
  app/controllers/application_controller.rb
  app/controllers/marcxml_controller.rb
  app/controllers/metadata_refresh_controller.rb
  app/controllers/objects_controller.rb
  app/models/symphony_reader.rb
  spec/controllers/marcxml_controller_spec.rb
  spec/models/symphony_reader_spec.rb
  spec/requests/metadata_refresh_spec.rb
  spec/requests/register_object_spec.rb
Labels: SDR Fall 2019, descMd problems

#392 surface Faraday::Timeout errors for Symphony response
  app/models/symphony_reader.rb
  spec/models/symphony_reader_spec.rb
Labels: SDR Fall 2019, descMd problems

#406 Do not allow objects to have multiple parents
  app/services/constituent_service.rb
  spec/services/constituent_service_spec.rb
Labels: SDR Fall 2019, virtual merge

#408 Add Sidekiq to process background jobs
  Capfile
  Gemfile
  Gemfile.lock
  README.md
  config/application.rb
  config/deploy.rb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/okcomputer.rb
  config/routes.rb
  config/sidekiq.yml
  docker-compose.yml
Labels: SDR Fall 2019, tech debt, virtual merge

#422 Handle virtual object creation in a background job
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/background_job_results_controller.rb
  app/controllers/virtual_objects_controller.rb
  app/jobs/application_job.rb
  app/jobs/create_virtual_objects_job.rb
  app/models/application_record.rb
  app/models/background_job_result.rb
  app/views/background_job_results/show.json.jbuilder
  config/application.rb
  config/database.yml
  config/routes.rb
  db/migrate/20190917215521_create_background_job_results.rb
  db/structure.sql
  docker-compose.yml
  openapi.json
  spec/factories/background_job_results.rb
  spec/jobs/create_virtual_objects_job_spec.rb
  spec/rails_helper.rb
  spec/requests/background_job_results_spec.rb
  spec/requests/batch_create_virtual_objects_spec.rb
  spec/support/factory_bot.rb
Labels: enhancement, tech debt, virtual merge

#441 deprecate sdr#current_version in favor of preservation-client
  Gemfile
  Gemfile.lock
  app/controllers/sdr_controller.rb
  app/services/sdr_client.rb
  app/services/version_service.rb
  config/initializers/preservation_client.rb
  config/routes.rb
  config/settings.yml
  openapi.json
  spec/controllers/sdr_controller_spec.rb
  spec/services/sdr_client_spec.rb
  spec/services/version_service_spec.rb
Labels: tech debt
